package essh

import (
	"bytes"
	"github.com/yuin/gopher-lua"
	"sort"
	"text/template"
)

type Host struct {
	Name        string
	SSHConfig   *lua.LTable
	Props       map[string]string
	Hooks       map[string][]interface{}
	Description string
	Hidden      bool
	Tags        []string
	Context     *Context
	Private     bool
}

var GlobalHosts map[string]*Host = map[string]*Host{}
var LocalHosts map[string]*Host = map[string]*Host{}
var PublicHosts map[string]*Host = map[string]*Host{}

func (h *Host) SortedSSHConfig() []map[string]string {
	values := []map[string]string{}

	var names []string

	h.SSHConfig.ForEach(func(k lua.LValue, v lua.LValue) {
		if keystr, ok := toString(k); ok {
			names = append(names, keystr)
		}
	})

	sort.Strings(names)

	for _, name := range names {
		lvalue := h.SSHConfig.RawGetString(name)
		if svalue, ok := toString(lvalue); ok {
			// can use only string value.
			value := map[string]string{name: svalue}
			values = append(values, value)
		}
	}

	return values
}

func (h *Host) DescriptionOrDefault() string {
	if h.Description == "" {
		return h.Name + " host"
	}

	return h.Description
}

func (h *Host) Scope() string {
	if h.Private {
		return "private"
	} else {
		return "public"
	}
}

func (h *Host) Key() string {
	return h.Context.TypeString() + ":" + h.Name
}

func GetPublicHost(hostname string) *Host {
	return PublicHosts[hostname]
}

func SortedHosts() []*Host {
	names := []string{}
	namesMap := map[string]bool{}
	hosts := []*Host{}

	for name, _ := range GlobalHosts {
		if namesMap[name] {
			// already registerd to names
			continue
		}

		names = append(names, name)
		namesMap[name] = true
	}

	for name, _ := range LocalHosts {
		if namesMap[name] {
			// already registerd to names
			continue
		}

		names = append(names, name)
		namesMap[name] = true
	}

	sort.Strings(names)

	for _, name := range names {
		if h, ok := GlobalHosts[name]; ok {
			hosts = append(hosts, h)
		}

		if h, ok := LocalHosts[name]; ok {
			hosts = append(hosts, h)
		}
	}

	return hosts
}

func SortedPublicHosts() []*Host {
	hosts := []*Host{}

	for _, h := range SortedHosts() {
		if !h.Private {
			hosts = append(hosts, h)
		}
	}

	return hosts

}

func SameContextHosts(contextType int) []*Host {
	hosts := []*Host{}

	for _, host := range SortedHosts() {
		if host.Context.Type == contextType {
			hosts = append(hosts, host)
		}
	}

	return hosts
}

var hostsTemplate = `# Generated by using https://github.com/kohkimakimoto/essh
# Don't edit this file manually.
{{range $i, $host := .Hosts}}
Host {{$host.Name}}{{range $ii, $param := $host.SortedSSHConfig}}{{range $k, $v := $param}}
    {{$k}} {{$v}}{{end}}{{end}}
{{end}}
`

func GenHostsConfig(enabledHosts []*Host) ([]byte, error) {
	tmpl, err := template.New("T").Parse(hostsTemplate)
	if err != nil {
		return nil, err
	}

	input := map[string]interface{}{"Hosts": enabledHosts}
	var b bytes.Buffer
	if err := tmpl.Execute(&b, input); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}

func Tags() []string {
	tagsMap := map[string]string{}
	tags := []string{}

	for _, host := range SortedHosts() {
		for _, t := range host.Tags {
			if _, exists := tagsMap[t]; !exists {
				tagsMap[t] = t
				tags = append(tags, t)
			}
		}
	}

	sort.Strings(tags)

	return tags
}

func FindHostsInContext(names []string, contextType int) []*Host {
	var hosts = []*Host{}

	for _, host := range SortedHosts() {
		if host.Context.Type != contextType {
			continue
		}

	B1:
		for _, name := range names {
			if host.Name == name {
				hosts = append(hosts, host)
				break B1
			}
		}

	B2:
		for _, tag := range host.Tags {
			for _, name := range names {
				if tag == name {
					hosts = append(hosts, host)
					break B2
				}
			}
		}
	}

	return hosts
}

func FindPublicHosts(names []string) []*Host {
	var hosts = []*Host{}

	for _, host := range SortedPublicHosts() {
	B1:
		for _, name := range names {
			if host.Name == name {
				hosts = append(hosts, host)
				break B1
			}
		}

	B2:
		for _, tag := range host.Tags {
			for _, name := range names {
				if tag == name {
					hosts = append(hosts, host)
					break B2
				}
			}
		}
	}

	return hosts
}

func HostsByNames(names []string) []*Host {
	var hosts = []*Host{}

	for _, host := range SortedHosts() {
	B1:
		for _, name := range names {
			if host.Name == name {
				hosts = append(hosts, host)
				break B1
			}
		}

	B2:
		for _, tag := range host.Tags {
			for _, name := range names {
				if tag == name {
					hosts = append(hosts, host)
					break B2
				}
			}
		}
	}

	return hosts
}

func HostsByTag(name string, isOnlyPublic bool) []*Host {
	var hosts = []*Host{}

	for _, host := range SortedHosts() {
	B1:
		for _, tag := range host.Tags {
			if tag == name {
				if isOnlyPublic {
					if !host.Private {
						hosts = append(hosts, host)
					}
				} else {
					hosts = append(hosts, host)
					break B1
				}
			}
		}
	}

	return hosts
}

func ResetHosts() {
	LocalHosts = map[string]*Host{}
	GlobalHosts = map[string]*Host{}
	PublicHosts = map[string]*Host{}

}
