# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant confiugre
Vagrant.configure(2) do |config|

  config.vm.define "webserver-01" do |c|
    c.vm.box = "centos/7"
    c.vm.hostname = "webserver-01"
    c.vm.network :private_network, type: "dhcp"
    c.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    c.ssh.insert_key = false

    # provisioning
    c.vm.provision :shell, :inline => <<-EOT
      ####################################
      # installing initial packages
      ####################################
      yum clean all
      yum install -y \
        curl \
        unzip \
        vim-enhanced \
        docker \
        git

      systemctl start docker
EOT
  end

  config.vm.define "webserver-02" do |c|
    c.vm.box = "centos/7"
    c.vm.hostname = "webserver-02"
    c.vm.network :private_network, type: "dhcp"
    c.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    c.ssh.insert_key = false

    # provisioning
    c.vm.provision :shell, :inline => <<-EOT
      ####################################
      # installing initial packages
      ####################################
      yum clean all
      yum install -y \
        curl \
        unzip \
        vim-enhanced \
        docker \
        git

      systemctl start docker
EOT
  end

end
